version: '3.7'

services:
  bot:
    container_name: tg_bot
    build: ./bot
    volumes:
      - ./bot/logs/:/bot/bot/logs
    restart: always
    
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

networks:
  default:
    name: bridge-nerwork
    external: true
    
